# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.

# Site Settings
title                    : "Junda Zhu, Ph.D."
description              : "Neuroscientist | Biomedical Engineer"
repository               : "ioqfwfq/ioqfwfq.github.io"
google_scholar_stats_use_cdn : true

# google analytics
google_analytics_id      : "G-XXXXXXXXXX"  # Replace with your actual Google Analytics ID

# SEO Related
google_site_verification : "PQ3f2uANGh_0bWdf9FERGuRDKvtHePTs4EkbfSf0IvI"
bing_site_verification   : "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"  # Add verification code from Bing Webmaster Tools

# Site Author
author:
  name             : "Junda Zhu, Ph.D."
  avatar           : "images/android-chrome-512x512.png"
  bio              : "Postdoctoral Scientist | Cedars-Sinai Medical Center"
  location         : "Los Angeles, CA"
  employer         : "Cedars-Sinai Medical Center"
  pubmed           :  # Optional: Link to PubMed search or author profile
  googlescholar    : "https://scholar.google.com/citations?user=jzhu2023"
  email            : "jzhu.neuro@gmail.com"
  researchgate     : "https://www.researchgate.net/profile/Junda-Zhu-9"
  github           : "ioqfwfq"
  linkedin         : "jundazhu"
  dblp             :  # e.g., "https://dblp.org/pid/xx/xxxx.html"
  orcid            : "https://orcid.org/0000-0002-0221-5289"
  twitter          : "JundaZhu"  # updated to correct X/Twitter handle

# Reading Files
include:
  - .htaccess
  - _pages
  - files
exclude:
  - docs
  - google_scholar_crawler
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - .github
  - CHANGELOG
  - Capfile
  - Gemfile
  - Gruntfile.js
  - LICENSE
  - README
  - Rakefile
  - assets/js/_main.js
  - assets/js/plugins
  - assets/js/vendor
  - config
  - gulpfile.js
  - log
  - node_modules
  - package.json
  - tmp
  - vendor
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"


# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false


# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Defaults
defaults:
  # _pages (English)
  - scope:
      path: ""
      type: pages
    values:
      layout: default
      author_profile: true
      
  # Chinese pages
  - scope:
      path: "_pages"
      type: pages
      lang: zh
    values:
      layout: default.zh
      author_profile: true

# URL
url: ""  # the base hostname & protocol for your site
baseurl: ""  # the subpath of your site, e.g. /blog

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed

# Outputting
permalink: /:categories/:title/
timezone: America/Los_Angeles

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-redirect-from

whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji

# HTML Compression
compress_html:
  clippings: all
  ignore:
    envs: development