# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.

# Site Settings
title                    : "Junda Zhu, Ph.D."
description              : "Neuroscientist | Engineer"
repository               : "ioqfwfq/ioqfwfq.github.io"
google_scholar_stats_use_cdn : true

# google analytics
google_analytics_id      : 

# SEO Related
google_site_verification : "PQ3f2uANGh_0bWdf9FERGuRDKvtHePTs4EkbfSf0IvI"
bing_site_verification   :  # Add verification code from Bing Webmaster Tools
baidu_site_verification  :  # Optional for Baidu

# Site Author
author:
  name             : "Junda Zhu, Ph.D."
  avatar           : "images/android-chrome-512x512.png"
  bio              : "Postdoctoral Scientist | Cedars-Sinai Medical Center"
  location         : "Los Angeles, CA"
  employer         : "Cedars-Sinai Medical Center"
  pubmed           :  # Optional: Link to PubMed search or author profile
  googlescholar    : "https://scholar.google.com/citations?user=REPLACE_WITH_YOUR_ID"
  email            : "jzhu.neuro@gmail.com"
  researchgate     : "https://www.researchgate.net/profile/Junda-Zhu"
  github           : "JundaZhu"
  linkedin         : "jundazhu"
  dblp             :  # e.g., "https://dblp.org/pid/xx/xxxx.html"
  orcid            : "https://orcid.org/0000-0002-XXXX-XXXX"  # replace with your ORCID
  twitter          : "@neuroJZhu"  # optional if you use Twitter

# Reading Files
include:
  - .htaccess
  - _pages
  - files
exclude:
  - docs
  - google_scholar_crawler
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - .github
  - CHANGELOG
  - Capfile
  - Gemfile
  - Gruntfile.js
  - LICENSE
  - README
  - Rakefile
  - assets/js/_main.js
  - assets/js/plugins
  - assets/js/vendor
  - config
  - gulpfile.js
  - log
  - node_modules
  - package.json
  - tmp
  - vendor
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"


# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false


# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Defaults
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: default

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed

# Outputting
permalink: /:categories/:title/
timezone: America/Los_Angeles

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-redirect-from

whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji

# HTML Compression
compress_html:
  clippings: all
  ignore:
    envs: development